user1 = User.create(name: "Trevor", email: "trevor@trevor.com", password: "trevor")

user2 = User.create(name: "Heather", email: "heather@heather.com", password: "heather")

user3 = User.create(name: "Harry", email: "harry@harry.com", password: "harry")

user4 = User.create(name: "Winston", email: "winston@winston.com", password: "winston")

user5 = User.create(name: "EP", email: "ep@ep.com", password: "ep")

user6 = User.create(name: "John", email: "john@john.com", password: "john")


game1 = Game.create(name: "Catan", user_id: 1)

game2 = Game.create(name: "Catan", user_id: 2)

game3 = Game.create(name: "Catan", user_id: 3)

game4 = Game.create(name: "Catan", user_id: 4)

game5 = Game.create(name: "Catan", user_id: 1)

game6 = Game.create(name: "Catan", user_id: 2)


turn1 = Turn.create(result: 2, game_id: 1)
turn2 = Turn.create(result: 3, game_id: 1)
turn3 = Turn.create(result: 4, game_id: 1)
turn4 = Turn.create(result: 5, game_id: 1)
turn5 = Turn.create(result: 6, game_id: 1)
turn6 = Turn.create(result: 7, game_id: 1)
turn7 = Turn.create(result: 8, game_id: 1)
turn8 = Turn.create(result: 9, game_id: 1)
turn9 = Turn.create(result: 10, game_id: 1)
turn10 = Turn.create(result: 11, game_id: 1)
turn11 = Turn.create(result: 12, game_id: 1)
turn12 = Turn.create(result: 3, game_id: 1)
turn13 = Turn.create(result: 4, game_id: 1)
turn14 = Turn.create(result: 5, game_id: 1)
turn15 = Turn.create(result: 6, game_id: 1)
turn16 = Turn.create(result: 7, game_id: 1)
turn17 = Turn.create(result: 8, game_id: 1)
turn18 = Turn.create(result: 9, game_id: 1)
turn19 = Turn.create(result: 10, game_id: 1)
turn20 = Turn.create(result: 11, game_id: 1)
turn21 = Turn.create(result: 12, game_id: 1)
turn22 = Turn.create(result: 3, game_id: 1)
turn23 = Turn.create(result: 4, game_id: 1)
turn24 = Turn.create(result: 5, game_id: 1)
turn25 = Turn.create(result: 6, game_id: 1)
turn26 = Turn.create(result: 7, game_id: 1)
turn27 = Turn.create(result: 8, game_id: 1)
turn28 = Turn.create(result: 9, game_id: 1)
turn29 = Turn.create(result: 10, game_id: 1)
turn30 = Turn.create(result: 4, game_id: 1)
turn31 = Turn.create(result: 5, game_id: 1)
turn32 = Turn.create(result: 6, game_id: 1)
turn33 = Turn.create(result: 7, game_id: 1)
turn34 = Turn.create(result: 8, game_id: 1)
turn35 = Turn.create(result: 9, game_id: 1)
turn36 = Turn.create(result: 10, game_id: 1)
turn37 = Turn.create(result: 6, game_id: 1)
turn38 = Turn.create(result: 7, game_id: 1)
turn39 = Turn.create(result: 8, game_id: 1)
turn40 = Turn.create(result: 9, game_id: 1)
turn41 = Turn.create(result: 10, game_id: 1)
turn42 = Turn.create(result: 6, game_id: 1)
turn43 = Turn.create(result: 7, game_id: 1)
turn44 = Turn.create(result: 8, game_id: 1)
turn44 = Turn.create(result: 9, game_id: 1)
turn45 = Turn.create(result: 10, game_id: 1)
turn46 = Turn.create(result: 6, game_id: 1)
turn47 = Turn.create(result: 7, game_id: 1)
turn48 = Turn.create(result: 8, game_id: 1)
turn49 = Turn.create(result: 9, game_id: 1)
turn50 = Turn.create(result: 10, game_id: 1)
turn51 = Turn.create(result: 6, game_id: 1)
turn52 = Turn.create(result: 7, game_id: 1)
turn53 = Turn.create(result: 9, game_id: 1)
turn54 = Turn.create(result: 10, game_id: 1)
turn55 = Turn.create(result: 6, game_id: 1)
turn56 = Turn.create(result: 7, game_id: 1)
turn57 = Turn.create(result: 9, game_id: 1)
turn58 = Turn.create(result: 10, game_id: 1)
turn59 = Turn.create(result: 6, game_id: 1)
turn60 = Turn.create(result: 7, game_id: 1)
turn61 = Turn.create(result: 9, game_id: 1)
turn62 = Turn.create(result: 10, game_id: 1)
turn63 = Turn.create(result: 6, game_id: 1)
turn64 = Turn.create(result: 7, game_id: 1)
turn65 = Turn.create(result: 9, game_id: 1)
turn56 = Turn.create(result: 6, game_id: 1)
turn67 = Turn.create(result: 7, game_id: 1)
turn68 = Turn.create(result: 9, game_id: 1)
turn69 = Turn.create(result: 6, game_id: 1)
turn70 = Turn.create(result: 7, game_id: 1)
turn71 = Turn.create(result: 6, game_id: 1)
turn72 = Turn.create(result: 7, game_id: 1)
turn73 = Turn.create(result: 6, game_id: 1)
turn74 = Turn.create(result: 7, game_id: 1)
turn75 = Turn.create(result: 7, game_id: 1)
turn76 = Turn.create(result: 7, game_id: 1)
turn77 = Turn.create(result: 7, game_id: 1)
turn78 = Turn.create(result: 7, game_id: 1)
turn79 = Turn.create(result: 7, game_id: 1)
turn80 = Turn.create(result: 7, game_id: 1)
turn81 = Turn.create(result: 7, game_id: 1)